---
slug: :suumo
depends:
  mikutter: 3.3.0
  plugin: []
version: '1.0'
author: toshi_a
name: suumo
description: 'ใโ๏ธmikutterโ๏ธ๐ใใณ๐ฅใใณ๐ฅใใณ๐ฅใทใฃใผใณ๐ถในใข๐ในใข๐ในใข๐ในใข๐ในใข ๐ในใข๐ในใใใใขโคด๐ใใซ๐ในใข๐ในใข๐ในใข๐ในใข๐ในใข๐ในใใใใขโคต๐'
